# Generated by Django 3.2.10 on 2021-12-25 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_auto_20211225_1349'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.major'),
        ),
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
